[package]
name = "dtags"
version = "0.0.0"
authors = ["Zach Ahn <engineering@zachahn.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
